### ISSUE TITLE
Bug Report: Invalid use of group function for sharded queries

### ISSUE THREAD

**Issue by olyazavr** [vitessio/vitess#11311]
### Overview of the Issue

Using Vitess 14 I'm getting `Invalid use of group function` for a query against a sharded db (works on unsharded): `SELECT sse.id, sse.portalId, sse.sequenceId, sse.enrollmentId, sse.sequenceStepId, sse.state, sse.stepOrder, sse.actionType, sse.delayMillis, sse.scheduledAtUpdatedAt, sse.scheduledAt, sse.timeOfDayMillis, sse.createdAt, sse.updatedAt, sse.trackerKey FROM sequence_step_enrollments AS sse JOIN (SELECT sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) AS stepOrder FROM sequence_step_enrollments AS sub WHERE sub.portalId = :portalId AND sub.enrollmentId IN (<enrollmentIds>) GROUP BY sub.portalId, sub.enrollmentId ORDER BY NULL) AS maxStep ON maxStep.portalId = sse.portalId AND maxStep.enrollmentId = sse.enrollmentId AND maxStep.stepOrder = sse.stepOrder WHERE sse.portalId = :portalId AND sse.enrollmentId IN (<enrollmentIds>)`

the query it seems to actually be executing is `select /*+ MAX_EXECUTION_TIME(30000) */ 1 from (select sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) as stepOrder from sequence_step_enrollments as sub where sub.portalId = :v1 and sub.enrollmentId in (:v2, :v3) and sub.portalId = :sse_portalId and sub.enrollmentId = :sse_enrollmentId and MAX(sub.stepOrder) = :sse_stepOrder group by sub.portalId, sub.enrollmentId order by null) as maxStep`

It works with the v3 planner but not gen4.

I tried rewriting the `MAX(sub.stepOrder)` as (`SELECT MAX(stepOrder) FROM ...)` but then I get `unknown type *physical.SubQueryOp pushJoinPredicates`

Slack convo: https://vitess.slack.com/archives/C0PQY0PTK/p1663785636835939

### Reproduction Steps

vschema:
```
{
  "sharded": true,
  "vindexes": {
    "hash": {
      "type": "hash"
    },
    "null": {
      "type": "null"
    }
  },
  "tables": {
    "sequence_step_enrollments": {
      "columnVindexes": [
        {
          "column": "portalId",
          "name": "hash"
        }
      ],
      "autoIncrement": {
        "column": "id",
        "sequence": "SequencesV2__sequence_step_enrollments__id__seq"
      }
    }
  }
}
```

schema:
```
mysql> show create table sequence_step_enrollments\G
*************************** 1. row ***************************
       Table: sequence_step_enrollments
Create Table: CREATE TABLE `sequence_step_enrollments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `portalId` int(10) unsigned NOT NULL,
  `sequenceId` bigint(20) unsigned NOT NULL,
  `enrollmentId` bigint(20) unsigned NOT NULL,
  `sequenceStepId` bigint(20) unsigned DEFAULT NULL,
  `state` tinyint(3) unsigned NOT NULL,
  `stepOrder` tinyint(3) unsigned NOT NULL,
  `actionType` tinyint(3) unsigned NOT NULL,
  `delayMillis` bigint(20) NOT NULL,
  `scheduledAtUpdatedAt` bigint(20) unsigned NOT NULL,
  `scheduledAt` bigint(20) unsigned NOT NULL,
  `createdAt` bigint(20) unsigned NOT NULL,
  `updatedAt` bigint(20) unsigned NOT NULL,
  `trackerKey` varchar(42) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `timeOfDayMillis` bigint(20) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_portalId_enrollmentId_stepOrder` (`portalId`,`enrollmentId`,`stepOrder`),
  KEY `idx_portalId_trackerKey` (`portalId`,`trackerKey`),
  KEY `idx_portalId_enrollmentId_state_actionType_scheduledAt` (`portalId`,`enrollmentId`,`state`,`actionType`,`scheduledAt`),
  KEY `idx_portalId_enrollmentId` (`portalId`,`enrollmentId`)
) ENGINE=InnoDB AUTO_INCREMENT=1628433300 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8
```

Run query
```
SELECT sse.id, sse.portalId, sse.sequenceId, sse.enrollmentId, sse.sequenceStepId, sse.state, sse.stepOrder, sse.actionType, sse.delayMillis, sse.scheduledAtUpdatedAt, sse.scheduledAt, sse.timeOfDayMillis, sse.createdAt, sse.updatedAt, sse.trackerKey FROM sequence_step_enrollments AS sse JOIN (SELECT sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) AS stepOrder FROM sequence_step_enrollments AS sub WHERE sub.portalId = 123 AND sub.enrollmentId IN (2) GROUP BY sub.portalId, sub.enrollmentId ORDER BY NULL) AS maxStep ON maxStep.portalId = sse.portalId AND maxStep.enrollmentId = sse.enrollmentId AND maxStep.stepOrder = sse.stepOrder WHERE sse.portalId = :portalId AND sse.enrollmentId IN (2)
```

### Binary Version

```sh
Version: 14.0.2-SNAPSHOT (Jenkins build 1)
```

### Operating System and Environment details

```sh
Can repro in both linux and macos
```

### Log Fragments

```sh
org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: 
java.sql.SQLSyntaxErrorException: message: "target: test_db_MgP1Tv.0.primary: vttablet: rpc error: code = InvalidArgument desc = Invalid use of group function (errno 1111) (sqlstate HY000) (CallerID: unsecure_grpc_client): Sql: \"select /*+ MAX_EXECUTION_TIME(30000) */ 1 from (select sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) as stepOrder from sequence_step_enrollments as sub where sub.portalId = :v1 and sub.enrollmentId in (:v2, :v3) and sub.state in (:v4, :v5, :v6, :v7, :v8, :v9, :v10, :v11, :v12) and sub.portalId = :sse_portalId and sub.enrollmentId = :sse_enrollmentId and MAX(sub.stepOrder) = :sse_stepOrder group by sub.portalId, sub.enrollmentId order by null) as maxStep /* user:unsecure_grpc_client */\", BindVars: {#maxLimit: \"type:INT64 value:\\\"10001\\\"\"sse_enrollmentId: \"type:UINT64 value:\\\"6670104721698623488\\\"\"sse_portalId: \"type:UINT32 value:\\\"1553004775\\\"\"sse_stepOrder: \"type:UINT8 value:\\\"1\\\"\"v1: \"type:INT64 value:\\\"1553004775\\\"\"v10: \"type:INT64 value:\\\"7\\\"\"v11: \"type:INT64 value:\\\"8\\\"\"v12: \"type:INT64 value:\\\"9\\\"\"v13: \"type:INT64 value:\\\"1553004775\\\"\"v14: \"type:INT64 value:\\\"6670104721698623488\\\"\"v15: \"type:INT64 value:\\\"9139429175885435904\\\"\"v16: \"type:INT64 value:\\\"1\\\"\"v17: \"type:INT64 value:\\\"2\\\"\"v18: \"type:INT64 value:\\\"3\\\"\"v19: \"type:INT64 value:\\\"4\\\"\"v2: \"type:INT64 value:\\\"6670104721698623488\\\"\"v20: \"type:INT64 value:\\\"5\\\"\"v21: \"type:INT64 value:\\\"6\\\"\"v22: \"type:INT64 value:\\\"7\\\"\"v23: \"type:INT64 value:\\\"8\\\"\"v24: \"type:INT64 value:\\\"9\\\"\"v3: \"type:INT64 value:\\\"9139429175885435904\\\"\"v4: \"type:INT64 value:\\\"1\\\"\"v5: \"type:INT64 value:\\\"2\\\"\"v6: \"type:INT64 value:\\\"3\\\"\"v7: \"type:INT64 value:\\\"4\\\"\"v8: \"type:INT64 value:\\\"5\\\"\"v9: \"type:INT64 value:\\\"6\\\"\"}"
code: INVALID_ARGUMENT
 [statement:"SELECT sse.id, sse.portalId, sse.sequenceId, sse.enrollmentId, sse.sequenceStepId, sse.state, sse.stepOrder, sse.actionType, sse.delayMillis, sse.scheduledAtUpdatedAt, sse.scheduledAt, sse.timeOfDayMillis, sse.createdAt, sse.updatedAt, sse.trackerKey FROM sequence_step_enrollments AS sse JOIN (SELECT sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) AS stepOrder FROM sequence_step_enrollments AS sub WHERE sub.portalId = :portalId AND sub.enrollmentId IN (<enrollmentIds>) AND sub.state IN (<stepEnrollmentStates>)GROUP BY sub.portalId, sub.enrollmentId ORDER BY NULL) AS maxStep ON maxStep.portalId = sse.portalId AND maxStep.enrollmentId = sse.enrollmentId AND maxStep.stepOrder = sse.stepOrder WHERE sse.portalId = :portalId AND sse.enrollmentId IN (<enrollmentIds>) AND sse.state IN (<stepEnrollmentStates>) ", located:"SELECT sse.id, sse.portalId, sse.sequenceId, sse.enrollmentId, sse.sequenceStepId, sse.state, sse.stepOrder, sse.actionType, sse.delayMillis, sse.scheduledAtUpdatedAt, sse.scheduledAt, sse.timeOfDayMillis, sse.createdAt, sse.updatedAt, sse.trackerKey FROM sequence_step_enrollments AS sse JOIN (SELECT sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) AS stepOrder FROM sequence_step_enrollments AS sub WHERE sub.portalId = :portalId AND sub.enrollmentId IN ((:__enrollmentIds_0_0),(:__enrollmentIds_1_0)) AND sub.state IN (:__stepEnrollmentStates_0,:__stepEnrollmentStates_1,:__stepEnrollmentStates_2,:__stepEnrollmentStates_3,:__stepEnrollmentStates_4,:__stepEnrollmentStates_5,:__stepEnrollmentStates_6,:__stepEnrollmentStates_7,:__stepEnrollmentStates_8)GROUP BY sub.portalId, sub.enrollmentId ORDER BY NULL) AS maxStep ON maxStep.portalId = sse.portalId AND maxStep.enrollmentId = sse.enrollmentId AND maxStep.stepOrder = sse.stepOrder WHERE sse.portalId = :portalId AND sse.enrollmentId IN ((:__enrollmentIds_0_0),(:__enrollmentIds_1_0)) AND sse.state IN (:__stepEnrollmentStates_0,:__stepEnrollmentStates_1,:__stepEnrollmentStates_2,:__stepEnrollmentStates_3,:__stepEnrollmentStates_4,:__stepEnrollmentStates_5,:__stepEnrollmentStates_6,:__stepEnrollmentStates_7,:__stepEnrollmentStates_8) ", rewritten:"SELECT /*+ MAX_EXECUTION_TIME(30000) */ sse.id, sse.portalId, sse.sequenceId, sse.enrollmentId, sse.sequenceStepId, sse.state, sse.stepOrder, sse.actionType, sse.delayMillis, sse.scheduledAtUpdatedAt, sse.scheduledAt, sse.timeOfDayMillis, sse.createdAt, sse.updatedAt, sse.trackerKey FROM sequence_step_enrollments AS sse JOIN (SELECT sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) AS stepOrder FROM sequence_step_enrollments AS sub WHERE sub.portalId = ? AND sub.enrollmentId IN ((?),(?)) AND sub.state IN (?,?,?,?,?,?,?,?,?)GROUP BY sub.portalId, sub.enrollmentId ORDER BY NULL) AS maxStep ON maxStep.portalId = sse.portalId AND maxStep.enrollmentId = sse.enrollmentId AND maxStep.stepOrder = sse.stepOrder WHERE sse.portalId = ? AND sse.enrollmentId IN ((?),(?)) AND sse.state IN (?,?,?,?,?,?,?,?,?) ", arguments:{ positional:{}, named:{__stepEnrollmentStates_5:6,__stepEnrollmentStates_6:7,__stepEnrollmentStates_7:8,portalId:1553004775,__stepEnrollmentStates_8:9,__stepEnrollmentStates_1:2,__stepEnrollmentStates_2:3,__enrollmentIds_1_0:9139429175885435904,__stepEnrollmentStates_3:4,__enrollmentIds_0_0:6670104721698623488,__stepEnrollmentStates_4:5,__stepEnrollmentStates_0:1}, finder:[]}]
	at com.hubspot.sequences.data.v2.sql.daos.sequencestepenrollments.SequenceStepEnrollmentsDaoTest.itFetchesMostRecentByState(SequenceStepEnrollmentsDaoTest.java:1329)
Caused by: java.sql.SQLSyntaxErrorException: 
message: "target: test_db_MgP1Tv.0.primary: vttablet: rpc error: code = InvalidArgument desc = Invalid use of group function (errno 1111) (sqlstate HY000) (CallerID: unsecure_grpc_client): Sql: \"select /*+ MAX_EXECUTION_TIME(30000) */ 1 from (select sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) as stepOrder from sequence_step_enrollments as sub where sub.portalId = :v1 and sub.enrollmentId in (:v2, :v3) and sub.state in (:v4, :v5, :v6, :v7, :v8, :v9, :v10, :v11, :v12) and sub.portalId = :sse_portalId and sub.enrollmentId = :sse_enrollmentId and MAX(sub.stepOrder) = :sse_stepOrder group by sub.portalId, sub.enrollmentId order by null) as maxStep /* user:unsecure_grpc_client */\", BindVars: {#maxLimit: \"type:INT64 value:\\\"10001\\\"\"sse_enrollmentId: \"type:UINT64 value:\\\"6670104721698623488\\\"\"sse_portalId: \"type:UINT32 value:\\\"1553004775\\\"\"sse_stepOrder: \"type:UINT8 value:\\\"1\\\"\"v1: \"type:INT64 value:\\\"1553004775\\\"\"v10: \"type:INT64 value:\\\"7\\\"\"v11: \"type:INT64 value:\\\"8\\\"\"v12: \"type:INT64 value:\\\"9\\\"\"v13: \"type:INT64 value:\\\"1553004775\\\"\"v14: \"type:INT64 value:\\\"6670104721698623488\\\"\"v15: \"type:INT64 value:\\\"9139429175885435904\\\"\"v16: \"type:INT64 value:\\\"1\\\"\"v17: \"type:INT64 value:\\\"2\\\"\"v18: \"type:INT64 value:\\\"3\\\"\"v19: \"type:INT64 value:\\\"4\\\"\"v2: \"type:INT64 value:\\\"6670104721698623488\\\"\"v20: \"type:INT64 value:\\\"5\\\"\"v21: \"type:INT64 value:\\\"6\\\"\"v22: \"type:INT64 value:\\\"7\\\"\"v23: \"type:INT64 value:\\\"8\\\"\"v24: \"type:INT64 value:\\\"9\\\"\"v3: \"type:INT64 value:\\\"9139429175885435904\\\"\"v4: \"type:INT64 value:\\\"1\\\"\"v5: \"type:INT64 value:\\\"2\\\"\"v6: \"type:INT64 value:\\\"3\\\"\"v7: \"type:INT64 value:\\\"4\\\"\"v8: \"type:INT64 value:\\\"5\\\"\"v9: \"type:INT64 value:\\\"6\\\"\"}"
code: INVALID_ARGUMENT
```
```

**Comment by systay** [comment]
Hi @olyazavr!

Thanks for reporting this! Sorry you where hit by yet another planner bug. 

We can see in the log fragment output what is going on:

```sql
where sub.portalId = :v1 and 
  sub.enrollmentId in (:v2, :v3) and 
  sub.state in (:v4, :v5, :v6, :v7, :v8, :v9, :v10, :v11, :v12) and 
  sub.portalId = :sse_portalId 
  and sub.enrollmentId = :sse_enrollmentId and 
  MAX(sub.stepOrder) = :sse_stepOrder
```

Here the planner thought that it would be a good idea to push the filter inside the derived table, which here means pushing in `MAX(sub.stepOrder) = :sse_stepOrder` to the `WHERE` clause, and that's not legal sql.

Fortunately, this was fixed in [recent work](https://github.com/vitessio/vitess/pull/11379) on `main`, and it should get backported to V14 soon.

**Comment by olyazavr** [comment]
Oh perfect, thank you!

**Comment by olyazavr** [comment]
@systay I pulled the latest v14 branch, and I'm still seeing this, for `Version: 14.0.3 (Jenkins build 3)` commit https://github.com/vitessio/vitess/commit/175c47a46c3dbe59aad9ec8f31b7aea2c3c21376

I can still get it to work by specifying the v3 planner, but it doesn't work with gen4

Full query:
`
SELECT /*+ MAX_EXECUTION_TIME(30000) */ sse.id, sse.portalId, sse.sequenceId, sse.enrollmentId, sse.sequenceStepId, sse.state, sse.stepOrder, sse.actionType, sse.delayMillis, sse.scheduledAtUpdatedAt, sse.scheduledAt, sse.timeOfDayMillis, sse.createdAt, sse.updatedAt, sse.trackerKey FROM sequence_step_enrollments AS sse JOIN (SELECT sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) AS stepOrder FROM sequence_step_enrollments AS sub WHERE sub.portalId = ? AND sub.enrollmentId IN ((?),(?)) AND sub.state IN (?,?,?,?,?,?,?,?,?)GROUP BY sub.portalId, sub.enrollmentId ORDER BY NULL) AS maxStep ON maxStep.portalId = sse.portalId AND maxStep.enrollmentId = sse.enrollmentId AND maxStep.stepOrder = sse.stepOrder WHERE sse.portalId = ? AND sse.enrollmentId IN ((?),(?)) AND sse.state IN (?,?,?,?,?,?,?,?,?)
`

Error:
`
tabletserver.go:1577] Invalid use of group function (errno 1111) (sqlstate HY000) (CallerID: unsecure_grpc_client): Sql: "select /*+ MAX_EXECUTION_TIME(30000) */ 1 from (select sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) as stepOrder from sequence_step_enrollments as sub where sub.portalId = :v1 and sub.enrollmentId in (:v2, :v3) and sub.state in (:v4, :v5, :v6, :v7, :v8, :v9, :v10, :v11, :v12) and sub.portalId = :sse_portalId and sub.enrollmentId = :sse_enrollmentId and MAX(sub.stepOrder) = :sse_stepOrder group by sub.portalId, sub.enrollmentId order by null) as maxStep /* user:unsecure_grpc_client */"
`

**Comment by systay** [comment]
ok, I’ve spent some time looking at this today. something weird is going on
the last error you posted is showing exactly the problem we fixed in the PR I linked to

```tabletserver.go:1577] Invalid use of group function (errno 1111) (sqlstate HY000) (CallerID: unsecure_grpc_client): Sql: "select /*+ MAX_EXECUTION_TIME(30000) */ 1 from (select sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) as stepOrder from sequence_step_enrollments as sub where sub.portalId = :v1 and sub.enrollmentId in (:v2, :v3) and sub.state in (:v4, :v5, :v6, :v7, :v8, :v9, :v10, :v11, :v12) and sub.portalId = :sse_portalId and sub.enrollmentId = :sse_enrollmentId and MAX(sub.stepOrder) = :sse_stepOrder group by sub.portalId, sub.enrollmentId order by null) as maxStep /* user:unsecure_grpc_client */"
```

the issue is with `MAX(sub.stepOrder) = :sse_stepOrder` that has been moved into the WHERE clause - that is not valid SQL

this was fixed in https://github.com/vitessio/vitess/pull/11379

When I try this on [175c47a](https://github.com/vitessio/vitess/commit/175c47a46c3dbe59aad9ec8f31b7aea2c3c21376), I get a query plan that looks good, with no `MAX` in the where clause:

```json
{
      "QueryType": "SELECT",
      "Original": "SELECT sse.id, sse.portalId, sse.sequenceId, sse.enrollmentId, sse.sequenceStepId, sse.state, sse.stepOrder, sse.actionType, sse.delayMillis, sse.scheduledAtUpdatedAt, sse.scheduledAt, sse.timeOfDayMillis, sse.createdAt, sse.updatedAt, sse.trackerKey FROM sequence_step_enrollments AS sse JOIN (SELECT sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) AS stepOrder FROM sequence_step_enrollments AS sub WHERE sub.portalId = 12 AND sub.enrollmentId IN (40,50,60) GROUP BY sub.portalId, sub.enrollmentId ORDER BY NULL) AS maxStep ON maxStep.portalId = sse.portalId AND maxStep.enrollmentId = sse.enrollmentId AND maxStep.stepOrder = sse.stepOrder WHERE sse.portalId = 12 AND sse.enrollmentId IN (1,2,3)",
      "Instructions": {
        "OperatorType": "Route",
        "Variant": "EqualUnique",
        "Keyspace": {
          "Name": "apa",
          "Sharded": true
        },
        "FieldQuery": "select sse.id, sse.portalId, sse.sequenceId, sse.enrollmentId, sse.sequenceStepId, sse.state, sse.stepOrder, sse.actionType, sse.delayMillis, sse.scheduledAtUpdatedAt, sse.scheduledAt, sse.timeOfDayMillis, sse.createdAt, sse.updatedAt, sse.trackerKey from sequence_step_enrollments as sse, (select sub.portalId, sub.enrollmentId, max(sub.stepOrder) as stepOrder from sequence_step_enrollments as sub where 1 != 1 group by sub.portalId, sub.enrollmentId) as maxStep where 1 != 1",
        "Query": "select sse.id, sse.portalId, sse.sequenceId, sse.enrollmentId, sse.sequenceStepId, sse.state, sse.stepOrder, sse.actionType, sse.delayMillis, sse.scheduledAtUpdatedAt, sse.scheduledAt, sse.timeOfDayMillis, sse.createdAt, sse.updatedAt, sse.trackerKey from sequence_step_enrollments as sse, (select sub.portalId, sub.enrollmentId, max(sub.stepOrder) as stepOrder from sequence_step_enrollments as sub where sub.portalId = 12 and sub.enrollmentId in (40, 50, 60) group by sub.portalId, sub.enrollmentId order by null) as maxStep where sse.portalId = 12 and sse.enrollmentId in (1, 2, 3) and maxStep.portalId = sse.portalId and maxStep.enrollmentId = sse.enrollmentId and maxStep.stepOrder = sse.stepOrder",
        "Table": "sequence_step_enrollments",
        "Values": [
          "INT64(12)"
        ],
        "Vindex": "hash"
      },
      "TablesUsed": [
        "apa.sequence_step_enrollments"
      ]
    }
```

My guess would be that you are somehow still trying an older build of vitess, but if you are sure you aren't, the next step would be to see if you can share the query plan that is being built.

You can use `explain format=vitess`, or the vtadmin query plan cache should also have it.

**Comment by olyazavr** [comment]
I've traced this back to supplying bindvars instead of resolved numbers:
```
-bind_variables "{\"v1\":1553004775, \"v2\":1553004775, \"v3\":6670104721698623488, \"v4\":6670104721698623488}" 
```
```
"SELECT sse.id, sse.portalId, sse.sequenceId, sse.enrollmentId, sse.sequenceStepId, sse.state, sse.stepOrder, sse.actionType, sse.delayMillis, sse.scheduledAtUpdatedAt, sse.scheduledAt, sse.timeOfDayMillis, sse.createdAt, sse.updatedAt, sse.trackerKey FROM sequence_step_enrollments AS sse JOIN (SELECT sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) AS stepOrder FROM sequence_step_enrollments AS sub WHERE sub.portalId = :v1 AND sub.enrollmentId IN (:v3) GROUP BY sub.portalId, sub.enrollmentId ORDER BY NULL) AS maxStep ON maxStep.portalId = sse.portalId AND maxStep.enrollmentId = sse.enrollmentId AND maxStep.stepOrder = sse.stepOrder WHERE sse.portalId = :v2 AND sse.enrollmentId IN (:v4)"
```

This triggers a difference [here](https://github.com/vitessio/vitess/blob/2286e1b1265df168632e63b2db8dc890ee94c4d1/go/vt/vtgate/planbuilder/operators/route_planning.go#L689) where the two sides are not equal because even though they resolve to the same numbers, the bind vars are different, and ergo they are not merged, the Route Type becomes Join instead of EqualUnique and the query is split into two queries, the first is

`select sse.portalId, sse.enrollmentId, sse.stepOrder from sequence_step_enrollments as sse where sse.portalId = ... and sse.enrollmentId in (...)`

and the second (invalid one) is

`select 1 from (select sub.portalId, sub.enrollmentId, MAX(sub.stepOrder) as stepOrder from sequence_step_enrollments as sub where sub.portalId = :v1 and sub.enrollmentId in (...) and sub.portalId = :sse_portalId and sub.enrollmentId = ... and MAX(sub.stepOrder) = :sse_stepOrder group by sub.portalId, sub.enrollmentId order by null) as maxStep`

The second one gets a select 1 prepended because of [this logic](https://github.com/vitessio/vitess/blob/2286e1b1265df168632e63b2db8dc890ee94c4d1/go/vt/vtgate/planbuilder/routeGen4.go#L134)

**Comment by olyazavr** [comment]
I wrote a test that fails with this in v14, but not in latest, time to figure out exactly what fixed this

**Comment by olyazavr** [comment]
The fix was https://github.com/vitessio/vitess/pull/10942

**Comment by systay** [comment]
@vitessio/query-serving we should backport the fix (https://github.com/vitessio/vitess/pull/10942) to V14

**Comment by systay** [comment]
It's been backported now
