### ISSUE TITLE
ERROR: initVtgateExecutor: json: cannot unmarshal bool into Go value of type map[string]json.RawMessage

### ISSUE THREAD

**Issue by justlooks** [vitessio/vitess#4475]
i try to use vtexplain as doc says ,but get error
```
$ vtexplain  -vschema-file /home/vitess/go/src/vitess.io/vitess/examples/local/vindex_legend_order_info.json -schema-file /home/vitess/go/src/vitess.io/vitess/examples/local/legend_order_info.sql -replication-mode "ROW"  -sql "SELECT * from legend_order_info"
ERROR: initVtgateExecutor: json: cannot unmarshal bool into Go value of type map[string]json.RawMessage

$ cat vindex_legend_order_info.json
{
  "sharded": true,
  "vindexes": {
    "hash": {
      "type": "hash"
    }
  },
  "tables": {
    "legend_order_info": {
      "column_vindexes": [
        {
          "column": "id",
          "name": "hash"
        }
      ]
    }
  }
}

```

**Comment by sougou** [comment]
Which binary are you using? I believe I fixed this bug recently.

**Comment by justlooks** [comment]
> Which binary are you using? I believe I fixed this bug recently.

```
$ vtctld -version
Version: 32dd398 (Git branch 'master') built on Wed Nov 28 16:57:57 CST 2018 by root@t-k8s-a1 using go1.11.1 linux/amd64
```

**Comment by demmer** [comment]
The problem here is that vtexplain expects a vschema for multiple keyspaces — i.e. the top level key in the json file should be the name of the keyspace, with the schema as you posted as the value.

This has bitten more than one person though, so I’m feeling like we should be more forgiving with the input format and accept either a single keyspace or a multi-keyspace vschema file.

**Comment by justlooks** [comment]
modified vschema file as @demmer  said ,still have some problem


```
$ cat vindex_legend_order_info_vtexplain.json
{
  "legend": {
  "sharded": true,
  "vindexes": {
    "hash": {
      "type": "hash"
    }
  },
  "tables": {
    "legend_order_info": {
      "column_vindexes": [
        {
          "column": "id",
          "name": "hash"
        }
      ]
    }
  }
 }
}

$ vtexplain  -vschema-file /home/vitess/go/src/vitess.io/vitess/examples/local/vindex_legend_order_info_vtexplain.json -schema-file /home/vitess/go/src/vitess.io/vitess/examples/local/legend_order_info.sql -replication-mode "ROW"  -sql "SELECT * from legend_order_info"
----------------------------------------------------------------------
SELECT * from legend_order_info

1 legend/-80: select * from legend_order_info limit 10001
1 legend/80-: select * from legend_order_info limit 10001

----------------------------------------------------------------------
E1221 14:10:04.559369   29114 conn.go:700] Error reading packet from client 4 (@): io.ReadFull(header size) failed: read unix /tmp/fakesqldb990238043/fakesqldb.sock->@: use of closed network connection
E1221 14:10:04.559434   29114 conn.go:700] Error reading packet from client 5 (@): io.ReadFull(header size) failed: read unix /tmp/fakesqldb990238043/fakesqldb.sock->@: use of closed network connection
E1221 14:10:04.559451   29114 conn.go:700] Error reading packet from client 6 (@): io.ReadFull(header size) failed: read unix /tmp/fakesqldb990238043/fakesqldb.sock->@: use of closed network connection
E1221 14:10:04.559464   29114 conn.go:700] Error reading packet from client 2 (@): io.ReadFull(header size) failed: read unix /tmp/fakesqldb990238043/fakesqldb.sock->@: use of closed network connection
E1221 14:10:04.559502   29114 conn.go:700] Error reading packet from client 3 (@): io.ReadFull(header size) failed: read unix /tmp/fakesqldb990238043/fakesqldb.sock->@: use of closed network connection
E1221 14:10:04.559592   29114 conn.go:700] Error reading packet from client 3 (@): io.ReadFull(header size) failed: read unix /tmp/fakesqldb062244094/fakesqldb.sock->@: use of closed network connection
E1221 14:10:04.559564   29114 conn.go:700] Error reading packet from client 2 (@): io.ReadFull(header size) failed: read unix /tmp/fakesqldb062244094/fakesqldb.sock->@: use of closed network connection
E1221 14:10:04.559613   29114 conn.go:700] Error reading packet from client 4 (@): io.ReadFull(header size) failed: read unix /tmp/fakesqldb062244094/fakesqldb.sock->@: use of closed network connection
E1221 14:10:04.559632   29114 conn.go:700] Error reading packet from client 5 (@): io.ReadFull(header size) failed: read unix /tmp/fakesqldb062244094/fakesqldb.sock->@: use of closed network connection
E1221 14:10:04.559659   29114 conn.go:700] Error reading packet from client 6 (@): io.ReadFull(header size) failed: read unix /tmp/fakesqldb062244094/fakesqldb.sock->@: use of closed network connection
```

**Comment by sougou** [comment]
Those errors can be ignored. The results look good. Your query got scattered to both shards.
